#!/usr/bin/env sh

# Wumpus moves
python wumpus_text.py --hmi=false --wumpus_dyn=true --verbose=false -e 10000 --runs=5
#ipython -i wumpus_text.py -- --hmi=false --wumpus_dyn=true --verbose=false -e 10000 --runs=5
